### ISSUE TITLE
QM9数据集合异常

### ISSUE THREAD

**Issue by heyfavour** [yuanqidu/LeftNet#1]
dimenet的作者说他的数据集是有问题的，你们可以使用pyg自带的QM9数据集来处理。
https://github.com/gasteigerjo/dimenet/blob/master/data/This%20dataset%20contains%20an%20off-by-one%20error!.md

**Comment by heyfavour** [comment]
另外正确数据集合的效果可否及时告知一下

**Comment by limei0307** [comment]
Hi @heyfavour, thanks for your information. We are looking into this and will update the dataset (perhaps with new results) soon.

**Comment by heyfavour** [comment]
> r information. We are looking into

可以使用pyg自带的QM9数据集么？

**Comment by heyfavour** [comment]
> Hi @heyfavour, thanks for your information. We are looking into this and will update the dataset (perhaps with new results) soon.

可以使用pyg自带的QM9数据集么？

**Comment by limei0307** [comment]
Hi @heyfavour, I think yes, we can use [torch_geometric.datasets.qm9](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/datasets/qm9.html#QM9) as it also provides atom types and atom positions. I need to double-check the position values and the property values.
