### ISSUE TITLE
Higher precision results on QM9 dataset

### ISSUE THREAD

**Issue by fmocking** [yuanqidu/LeftNet#2]
Hello,

I want to begin by expressing my sincere gratitude for sharing your remarkable work. Your contributions are truly invaluable to the field.

I had a question regarding the reported results for the QM9 dataset. In the current version, the G target value is provided as an integer (e.g., G=6). However, I noticed that some previous works have reported results with decimal places for this dataset, providing more precise values.

If possible, would you be willing to share the results for all targets with decimal-place precision? Having access to these more precise values would enable a more thorough analysis and comparison of your impressive findings.

I understand that this request may require additional effort on your part. Please let me know if there are any constraints or considerations I should keep in mind. Any level of additional precision you can provide would be greatly appreciated.

Thank you once again for your significant contributions and for considering my request. 

Best regards,

**Comment by yuanqidu** [comment]
Sorry for the late reply, here are the results with more precisions
Top row
G 6.9
H 5.6
U 7.4
U0 5.5

Bottom row
G 6.1
H 5.0
U 5.2
U0 4.7

**Comment by yuanqidu** [comment]
Let me know if you are also interested in results in more precision.
