### ISSUE TITLE
A minor issue in the code

### ISSUE THREAD

**Issue by e-yi** [yuanqidu/LeftNet#5]
https://github.com/yuanqidu/LeftNet/blob/326ad6d2c6f06a0300c7b98b7cdd97f7926e91fc/model.py#L224

I believe this line is supposed to be as follows
```
 dx = xvec1 + xvec2 * vec_dot
```

**Comment by yuanqidu** [comment]
Uh you are right, it makes more sense to use it to scale the vectors (as we followed PaiNN on that), but the code was what we ran to obtain the results. If you have results on the fixed implementation, we would be curious to know!
