### ISSUE TITLE
The node frame has no effect in the code

### ISSUE THREAD

**Issue by e-yi** [yuanqidu/LeftNet#6]
https://github.com/yuanqidu/LeftNet/blob/326ad6d2c6f06a0300c7b98b7cdd97f7926e91fc/model.py#L208

It is used to compute `scalrization` in FTE, but `scalrization` does not contribute to any of the outputs.

**Comment by e-yi** [comment]
https://github.com/yuanqidu/LeftNet/blob/326ad6d2c6f06a0300c7b98b7cdd97f7926e91fc/model.py#L210

My guess is this line

```
scalar = torch.norm(vec1, dim=-2)
```

should be

```
scalar = torch.norm(scalrization , dim=-2) 
```

**Comment by yuanqidu** [comment]
Thank you for catching it! Indeed, we tried multiple ways of incorporating it but didn't use it in the final version of the code. The scalars are flexible to be used in any part of the features.
